@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Nov 14 22:19:19 -0500 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto c54f172dc8c64f399bb3b9f6918b0474 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot twosC_1bit_behav xil_defaultlib.twosC_1bit -log elaborate.log"
call xelab  -wto c54f172dc8c64f399bb3b9f6918b0474 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot twosC_1bit_behav xil_defaultlib.twosC_1bit -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
